#! /usr/bin/env bash

export VERIFY_TOKEN='mybot'
export PAGE_ACCESS_TOKEN='EAAZAf662Ou1gBAMvDSqzGwZB9fxY8fvcsJsFPfTMrZBNoAp23Whi9zZBEtZAWJGvlrnpu2GAka8FkW7g0n8oYsGIrw1DJ4yZBpi3UXRmM8kQgn1cbfSBQQ0t8eROlFnaJCZARdWlelZBeeBNRZCZCK9FZC9UN3zSON6aBikvcY2bvieZBAZDZD'

# Get started message
curl -X POST -H "Content-Type: application/json" -d '{
  "get_started":{
    "payload": "GET_STARTED_PAYLOAD"
  }
}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token="$PAGE_ACCESS_TOKEN

# Greeting text
curl -X POST -H "Content-Type: application/json" -d '{
  "greeting":[
    {
      "locale":"default",
      "text":"3, 2, 1... MEME IT RIP!"
    }, {
      "locale":"en_US",
      "text":"Help scientists understand today´s world through memes!"
    }
  ]
}' "https://graph.facebook.com/v2.6/me/messenger_profile?access_token="$PAGE_ACCESS_TOKEN

# Run app
python bot.py
